let var1=true;
let var2=false;
let var3=null;
let var4=undefined;
let var5='';
let var6=NaN;
let var7=10;
let var8=0;
console.log(Boolean(var1));
console.log(Boolean(var2));
console.log(Boolean(var3));
console.log(Boolean(var4));
console.log(Boolean(var5));
console.log(Boolean(var6));
console.log(Boolean(var7));
console.log(Boolean(var8));
